on:
    push:
      branches:
        - 'main'
    schedule:
      - cron: '0 0 * * *'
jobs:
    build:
        #runs-on: self-hosted
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Extract short SHA
          id: short_sha
          run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        - uses: actions/github-script@v6
          id: get_release
          with:
            script: |
              const release = await github.rest.repos.getLatestRelease({
                owner: 'wspr-ncsu',
                repo: 'visiblev8'
              });
              const tag = release.data.tag_name;
              const currentGitCommit = '${{ steps.short_sha.outputs.sha_short }}'
              const [_, commit, fullVersion, majorVersion] = tag.match(/visiblev8_([0-9a-f]+)-(([0-9]+)\.[0-9.]+)/);
              const chromeReleaseVersion = await (await fetch('https://omahaproxy.appspot.com/linux')).text();
              console.log(`tag: ${tag}`);
              console.log(`commit: ${commit}`);
              console.log(`fullVersion: ${fullVersion}`);
              console.log(`majorVersion: ${majorVersion}`);
              console.log(`currentGitCommit: ${currentGitCommit}`);
              console.log(`chromeReleaseVersion: ${chromeReleaseVersion}`);
              const shouldPublish = currentGitCommit !== commit || chromeReleaseVersion !== majorVersion;
              console.log(`shouldPublish: ${shouldPublish}`);
              return {
                shouldPublish,
                tag,
                commit,
                fullVersion,
                majorVersion
              };
        - name: Test version number
          run: |
            echo "shouldPublish=${{ steps.get_release.outputs.result.shouldPublish }}"
            echo "tag=${{ steps.get_release.outputs.result.tag }}"
            echo "commit=${{ steps.get_release.outputs.result.commit }}"
            echo "fullVersion=${{ steps.get_release.outputs.result.fullVersion }}"
            echo "majorVersion=${{ steps.get_release.outputs.result.majorVersion }}"
        - name: Build VisibleV8
          if: ${{ steps.get_release.outputs.result.shouldPublish == 'true' }}
          env:
            VERSION: ${{ steps.get_release.outputs.result.fullVersion }}
          run: |
            cd builder && make build VERSION=$VERSION DEBUG=0 PUBLISH_ASSETS=1 TESTS=1 ANDROID=1
