on:
  push:
    branches:
      - 'main'
jobs:
  upload_to_docker:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Use a caching step
        uses: actions/cache@v3
        with:
          path: |
            ./post-processor/tracker-radar
          key: ${{ runner.os }}-build-artifacts
      - name: Build postprocessors
        uses: ./.github/build-postprocessors
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: sohomdatta1
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract short SHA
        id: short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: sohomdatta1/visiblev8-postprocessors
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{ steps.short_sha.outputs.sha_short }},enable=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./post-processor/
          file: ./post-processor/build/Dockerfile.vv8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Remove artifacts
        uses: docker://ubuntu:latest
        with:
          entrypoint: /usr/bin/rm
          args: -rf ./post-processor/artifacts


