on:
  push:
    branches:
      - 'main'
jobs:
  upload_to_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build postprocessors
        uses: ./actions/build


