on:
  push:
    branches:
      - 'main'
jobs:
  upload_to_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Use a caching step
        uses: actions/cache@v3
        with:
          path: |
            ./post-processor/tracker-radar
          key: ${{ runner.os }}-build-artifacts
      - name: Build postprocessors
        uses: ./.github/build-postprocessors
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: sohomdatta1/visiblev8-postprocessors
          tags: |
            latest
            ${{ github.sha }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./post-processor/
          file: ./post-processor/build/Dockerfile.vv8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


